NAME		= brainz

SRCS		= main.cpp \
			  newZombie.cpp \
			  Zombie.cpp \
			  randomChump.cpp

OBJS		= $(SRCS:.cpp=.o)

CC			= c++
RM			= rm -f
CPPFLAGS	= -Wall -Wextra -Werror -std=c++98

all:		$(NAME)

$(NAME):	$(OBJS)
			$(CC) $(CPPFLAGS) $(OBJS) -o $(NAME)

clean:
			$(RM) $(OBJS)

fclean:		clean
			$(RM) $(NAME)

re:			fclean all

.PHONY:		all clean fclean re